--- openzwave-1.0.791/cpp/build/Makefile	2014-04-29 13:40:54.000000000 +0800
+++ openzwave-1.0.791/cpp/build/Makefile.out	2014-09-06 13:14:25.898122147 +0800
@@ -177,8 +177,10 @@
 	install -m 0644 $(top_srcdir)/cpp/src/platform/*.h $(DESTDIR)/$(includedir)/platform/	
 	install -d $(DESTDIR)/$(includedir)/platform/unix/
 	install -m 0644 $(top_srcdir)/cpp/src/platform/unix/*.h $(DESTDIR)/$(includedir)/platform/unix/
-	install -d $(DESTDIR)/$(sysconfdir)/
-	cp -r $(top_srcdir)/config/* $(DESTDIR)/$(sysconfdir)
+	install -d $(DESTDIR)/$(includedir)/tinyxml
+	install -m 0644 $(top_srcdir)/cpp/tinyxml/*.h $(DESTDIR)/$(includedir)/tinyxml/
+	install -d $(DESTDIR)/$(sysconfdir)/openzwave
+	cp -r $(top_srcdir)/config/* $(DESTDIR)/$(sysconfdir)/openzwave
 	install -d $(DESTDIR)/$(docdir)/
 	cp -r $(top_srcdir)/docs/* $(DESTDIR)/$(docdir)
 	if [ -d "$(top_builddir)/docs/html/" ]; then cp -r $(top_builddir)/docs/html/* $(DESTDIR)/$(docdir); fi
