--- openzwave-1.0.791/cpp/build/Makefile	2014-09-05 14:09:56.166585422 +0800
+++ openzwave-1.0.791/cpp/build/Makefile.out	2014-09-05 14:07:05.682578099 +0800
@@ -171,6 +171,8 @@
 	install -m 0644 $(top_srcdir)/cpp/src/*.h $(DESTDIR)/$(includedir)
 	install -d $(DESTDIR)/$(includedir)/command_classes/
 	install -m 0644 $(top_srcdir)/cpp/src/command_classes/*.h $(DESTDIR)/$(includedir)/command_classes/
+	install -d $(DESTDIR)/$(includedir)/tinyxml/
+	install -m 0644 $(top_srcdir)/cpp/tinyxml/*.h $(DESTDIR)/$(includedir)/tinyxml/
 	install -d $(DESTDIR)/$(includedir)/value_classes/
 	install -m 0644 $(top_srcdir)/cpp/src/value_classes/*.h $(DESTDIR)/$(includedir)/value_classes/
 	install -d $(DESTDIR)/$(includedir)/platform/
