--- git/src/makefile	2021-12-07 16:18:53.958681971 +0800
+++ git/src/makefile.new	2021-12-07 16:20:26.076162985 +0800
@@ -172,12 +172,12 @@
 # for Linux
 SO_linux=so
 O_linux=o
-CC_linux=gcc
+CC_linux=${GCC_linux}
 DEF_linux=-DLUASOCKET_$(DEBUG)
 CFLAGS_linux=$(LUAINC:%=-I%) $(DEF) -Wall -Wshadow -Wextra \
 	-Wimplicit -O2 -ggdb3 -fpic
 LDFLAGS_linux=-O -shared -fpic -o 
-LD_linux=gcc
+LD_linux=${GCC_linux}
 SOCKET_linux=usocket.o
 
 #------
