--- git/src/makefile        2018-03-06 22:29:37.365213209 +0800
+++ git/src/makefile        2018-03-06 22:30:07.104721223 +0800
@@ -164,7 +164,7 @@
 # for Linux
 SO_linux=so
 O_linux=o
-CC_linux=gcc
+CC_linux=${GCC_linux}
 DEF_linux=-DLUASOCKET_$(DEBUG) \
        -DLUASOCKET_API='__attribute__((visibility("default")))' \
        -DUNIX_API='__attribute__((visibility("default")))' \
@@ -172,7 +172,7 @@
 CFLAGS_linux= -I$(LUAINC) $(DEF) -Wall -Wshadow -Wextra \
        -Wimplicit -O2 -ggdb3 -fpic -fvisibility=hidden
 LDFLAGS_linux=-O -shared -fpic -o 
-LD_linux=gcc
+LD_linux=${GCC_linux}
 SOCKET_linux=usocket.o
 
 #------

