--- ./makefile.original	2018-03-07 09:29:54.263910827 +0800
+++ ./makefile	2018-03-07 09:31:18.930690576 +0800
@@ -1,7 +1,7 @@
 LIBNAME = lpeg
-LUADIR = ../lua/
+LUADIR = ${LUA_DIR}
 
-COPT = -O2
+COPT ?= -O2
 # COPT = -DLPEG_DEBUG -g
 
 CWARNS = -Wall -Wextra -pedantic \
@@ -21,9 +21,8 @@
 	-Wstrict-prototypes \
 # -Wunreachable-code \
 
-
-CFLAGS = $(CWARNS) $(COPT) -std=c99 -I$(LUADIR) -fPIC
-CC = gcc
+CFLAGS ?= $(CWARNS) $(COPT) -std=c99 -I$(LUADIR) -fPIC
+CC ?= gcc
 
 FILES = lpvm.o lpcap.o lptree.o lpcode.o lpprint.o
 
